= loccount(1) =
:doctype: manpage

== NAME ==
loccount - count lines of code in a source tree and perform cost estimation

== SYNOPSIS ==
*loccount* [-c] [-e] [-i] [-l] [-s] [-u] [-x pathlist] [-V] [-?] file-or-dir...

== DESCRIPTION ==

This program counts physical source lines of code (SLOC) and logical
lines of code (LLOC) in one or more files or directories given on the
command line.

A line of code is counted in SLOC if it (a) includes characters other
than whitespace and a terminating newline, and (b) is not composed
solely of a comment or part of a comment.  Comment leaders and
trailers in string literals (including multiline string literals) in
languages that have them) are ignored.

LLOC is counted by tallying SLOCs with line terminators. In C like
languages, preprocessor directives including #define, #include, and
Objective-C #import are also counted as a LLOC each.

LLOC reporting is not available in all supported languages, as the
concept may not fit the langage's syntax (e.g. the Lisp family) or its
line-termination rules would require full parsing (e.g. Go). In these
case LLOC will always be reported as 0. It is quite reliable in
languages with C-like statement termination by semicolon.

Optionally, this program can perform a cost-to-replicate estimation
using the COCOMO I and (if LLOC count is nonzero) COCOMO II models. It
uses the "organic" profile of COCOMO, which is generally appropriate
for open-source projects.

SLOC/LLOC figures should be used with caution.  While they do predict
project costs and defect incidence reasonably well, they are not
appropriate for use as 'productivity' measures; good code is often
less bulky than bad code.  Comparing SLOC across languages is also
dubious, as differing languages can have very different complexity per
line.

With these qualifications, SLOC/LLOC does have some other uses. It
is quite effective for tracking changes in complexity and attack
surface as a codebase evolves over time.

All languages in common use on Unix-like operating systems are
supported.  For a full list of supported languages, run "loccount -s";
loccount -l lists languages for which LLOC computation is
available. Note that (1) "shell" includes bash, dash, ksh, and other
similar variants descended from the Bourne shell, and (2) the language
"c-header" is a marker for C-style include (.h) files which will be
assigned to the dominant C-family language in a report (if there is
one).

The program also emits counts for build recipes - Makefiles, autoconf
specifications, scons recipes, and waf scripts. Generated Makefiles
are recognized and ignored.

Languages are recognized by file extension or filename pattern;
executable filenames without an extension are mined for #! lines
identifying an interpreter.  Files that cannot be classified in
this way are skipped, but a list of files skipped in this way
is available with the -u option.

Some file types are identified and silently skipped without being
reported by -u; these include symlinks, .o, .a, and .so object files,
various kinds of image and audio files, and the .pyc/.pyo files
produced by the Python interpreter.  All files and directories named
with a leading dot are also silently skipped (in particular, this
ignores metadata associated with version-control systems).

== OPTIONS ==
-?::
Display usage summary and quit.

-c::
Report COCOMO cost estimates. Use the coefficients for the
"organic" project type, which fits most open-source
projects.  An EAF of 1.0 is assumed.

-d _n_::
Set debug level. At > 0, displays various progress messages.  Mainly
of interest to loccount developers.

-e::
Show the association between languages and file extensions.

-i::
Report file path, line count, and type for each individual path.

-j::
Dump the results as self-describing JSON records for for postprocessing.

-l::
List languages for which we can report LLOC and exit. Combine with -i
to list languages one per line.

-s::
List languages for which we can report SLOC and exit.

-u::
List paths of files that could not be classified into a type.

-x _prefix_::
Ignore paths maching the specified Go regular expression. 

-V::
Show program version and exit.

Arguments following options may be either directories or files.
Directories are recursed into. The report is generated on all
paths specified on the command line.

== HISTORY AND COMPATIBILITY ==

The algorithms in this code originated with David A. Wheeler's
*sloccount* utility, version 2.26 of 2004.  It is, however, faster
than sloccount, and handles many languages that sloccount does not.

Generally it will produce identical SLOC figures to sloccount for a
language supported by both tools; the differences in whole-tree
reports will mainly be due to better detection of some files sloccount
left unclassified. Notably, for individual C and Perl files
you can expect both tools to produce identical SLOC. However,
Python counts are different, because sloccount does not recognize
and ignore single-quote multiline literals.

A few of sloccount's tests have been simplified in cases where the
complexity came from a rare or edge case that the author judges to
have become extinct since 2004.

The reporting formats of loccount 2.x are substantially different from
those in the 1.x versions due to absence of any LLOC fields in 1.x.

The base salary used for cost estimation will differ between these
tools depending on time of last release.

== BUGS ==

The sloccount logic for treating multiple argument directories as different
projects has not been reproduced. This may change in a future release.

Nesting block comments in languages that allow this (such as Rust,
Haskell, or D) will confuse the line counting, resulting in overcounts
after the deepest comment exit is reached.

PHP #-comments taking up an entire line or following only whitespace
on a line will be counted, not recognized as comments and skipped.

In lua, only the zero-level block comment syntax beginning --[[ is
recognized as a comment.

Eiffel indexing comments are counted as code, not text. (This is
arguably a feature.)

The asm counter assumes ";" winged comments. This is correct for Intel
assemblers and some others, but not all.  GAS uses "#".

In lex, flex, yacc, and bison files, block comments beginning within string
literals will confuse this program and throw a warning.

Literate Haskell (.lhs) is not supported.  (This is a regression from
sloccount).

Ruby, Simula, and Algol 60 block comments are not recognized.

LLOC counts in languages that use a semicolon as an Algol-like
statement separator, rather than a terminator, will be less accurate.
When these require a semi after an end of block - Sather, Simula, CLU,
- counts will run somewhat too high, because "end" is counted as a
statement.  Conversely, reported LLOC will be a bit low in languages
like Pascal, Modula, and Oberon that don't require a semi either after
the last statement in the block or the block end.

== REPORTING BUGS ==
Report bugs to Eric S. Raymond <esr@thyrsus.com>.
